image: python:3.9-bullseye
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get install --assume-yes pandoc
  - pip install numpy pandas termcolor paho-mqtt zmq  # top import of Ohmpi.py
  - pip install sphinx numpydoc sphinx_rtd_theme pandoc recommonmark linuxdoc
  - cp configs/config_default.py ohmpi/config.py  # only compile doc with dummy if not on rpi with correct config.py
  - cd doc
  - make html
  
  # also make latex? pdf?
  - cd ..
  - mv doc/build/html/ public/
  - ls public/
  artifacts:
    paths:
    - public/
  only:
  - master

before_script:
  - apt-get update -y
  - apt-get install -y jq curl

make-badge:
  stage: deploy
  script:
    - version=$(cat version.txt)
    - version_badge_id=$(curl --header "PRIVATE-TOKEN:${API_TOKEN}" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/badges | jq -c 'map(select(.name | contains("version")))[0].id')
    - curl --request PUT --header "PRIVATE-TOKEN:${API_TOKEN}" --data "image_url=https://img.shields.io/badge/version-${version}-blue" https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/badges/${version_badge_id}

