M48
; DRILL file {KiCad (6.0.9)} date Fri Feb 24 15:44:54 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-24T15:44:54+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X7.8232Y-3.5827
X7.8232Y-5.8661
X9.7524Y-3.5827
X9.7524Y-5.8661
T0
M30
